# Generated by Django 6.0.4 on 2026-05-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('column_layout', models.CharField(choices=[('ONE', '1 Column'), ('TWO', '2 Column'), ('THREE', '3 Column')], default='ONE', max_length=10)),
                ('show_divider', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sections', to='restapi.templatemaster')),
            ],
            options={
                'db_table': 'template_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('DECIMAL', 'Decimal'), ('TIME', 'Time'), ('DROPDOWN', 'Dropdown'), ('UPLOAD', 'Upload File'), ('DIVIDER', 'Divider')], max_length=20)),
                ('sublabel', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('column_position', models.PositiveIntegerField(default=1)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='restapi.templatesection')),
            ],
            options={
                'db_table': 'template_field',
                'ordering': ['order'],
            },
        ),
    ]
