# Generated by Django 6.0.4 on 2026-05-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_templatesection_templatefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='sublabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
