name: TEMPLATE BACKEND PUSHTRIGGER

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend Docker Image
      - name: Build Docker image
        run: |
          docker build --no-cache \
          -f devops/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/template-backend:latest \
          .

      # Push Backend Image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/template-backend:latest

      # Deploy Backend to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Pull latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/template-backend:latest

            echo "Stop old container"
            docker ps -aq --filter "name=template-backend" | xargs -r docker stop
            docker ps -aq --filter "name=template-backend" | xargs -r docker rm

            echo "Start new container"
            docker run -d \
              --restart always \
              --name template-backend \
              -p 8005:8000 \
              ${{ secrets.DOCKER_USERNAME }}/template-backend:latest

            echo "Wait container boot"
            sleep 12
                   
            echo "Run database migrations"
            docker exec template-backend python manage.py migrate || true
